name: Build and Test Gradle Project

on:
  push:
    branches:
      - main
      - circom-testing
  pull_request:
    branches:
      - main
      - circom-testing

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: code-generator

    - name: Test with Gradle
      run: ./gradlew test
      working-directory: code-generator